repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/zerosnake0/pre-commit-hooks
    rev: v0.0.5
    hooks:
      - id: gofmt
      - id: goimports
