language: go

go:
#  - 1.10.x
#  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

env:
  - GO111MODULE=on

script:
  - go test -tags debug -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  allow_failures:
    - if: branch != master
      go: tip

  exclude:
    - if: branch = master
      go: tip
