name: Test
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on:  ${{ matrix.platform }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -tags debug -race ./...

    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash)
