name: Test
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    runs-on:  ${{ matrix.platform }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    #- name: Get dependencies
    #  run: |
    #    go get -v -t -d ./...
    #    if [ -f Gopkg.toml ]; then
    #        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #        dep ensure
    #    fi

    - name: Test
      run: go test -race ./...
